#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Release

#Toolchain
PREFIX ?= arm-linux-gnueabihf
CC := $(PREFIX)-gcc
CXX := $(PREFIX)-g++
LD := $(CXX)
AR := $(PREFIX)-ar
OBJCOPY := $(PREFIX)-objcopy

#Additional flags
PREPROCESSOR_MACROS := NDEBUG=1 RELEASE=1
INCLUDE_DIRS := 
#INCLUDE_DIRS := $(TOOLCHAIN_ROOT)/arm-linux-gnueabihf/libc/usr/include
LIBRARY_DIRS := 
LIBRARY_NAMES := 
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O3
CXXFLAGS := -ggdb -ffunction-sections -O3
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := -march=armv7-a -mfloat-abi=hard -mfpu=neon
LINKER_SCRIPT := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 0
CP_NOT_AVAILABLE := 1
IS_LINUX_PROJECT := 1
